# Generated by Django 3.1.7 on 2021-08-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210801_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth',
            new_name='birthday',
        ),
    ]
